### ISSUE TITLE
v 2.11.0

### ISSUE THREAD

**Issue by tamarklg** [hebcal/hebcal-es6#17]
@mjradwin  I used till now version 2.6.1, and it worked perfect.
I upgraded to latest version, and when I try to use new HDate(), I get the following error: "ERROR TypeError: _hebcal_core__WEBPACK_IMPORTED_MODULE_1__.HDate is not a constructor"

**Comment by mjradwin** [comment]
Hi, thanks for the bug report. Our sincere apologies for the issue.

We've fixed this breaking change in @hebcal/core@2.12.0 - please update and confirm that it works for you.

**Comment by tamarklg** [comment]
Thanks for your quick reply, but it didn't solve the problem. Still get the same error.
