### ISSUE TITLE
Unexpected LIGHT_CANDLES Mask Value (5) for Shabbos Parashat Ha'azinu

### ISSUE THREAD

**Issue by meyer59** [hebcal/hebcal-es6#451]
Hi,
We have an app that shows the candle lighting times for every Shabbos. To achieve this, we filter using the mask LIGHT_CANDLES (2) according to [the documentation](https://github.com/hebcal/hebcal-es6/blob/322b57acb08281231c2d2a37280c51d1ff758567/src/event.ts#L14).

However, with Rosh Hashanah approaching, the app suddenly stopped working. After investigating, we noticed that for Shabbos Parashat Ha'azinu, the LIGHT_CANDLES mask has a value of 5. According to the documentation, there is no mask value for 5. Is this a bug?
Thank you for your help

we use hebcal/core@5.5.0

**Comment by mjradwin** [comment]
The Event flags are a bitmask, and therefore you need to test with something like this

```js
if (ev.getFlags() & flags.LIGHT_CANDLES) {
  // ...
}
```

A value of 5 is the bitwise-OR of `CHAG` and `YOM_TOV_ENDS`

**Comment by meyer59** [comment]
But it shows candle ligthing so it should be a flags.LIGHT_CANDLES no? screenshot below index 5
![image (23)](https://github.com/user-attachments/assets/9ad12dcc-c1ff-4d60-b4ba-b46e2e08b763)

**Comment by mjradwin** [comment]
Thanks - yes, we agree, the Friday night candle-lighting event should have flags.LIGHT_CANDLES. We won't be able to fix this before Rosh Hashana, but we can try to get this fixed before Shabbat Chol HaMoed Sukkot

**Comment by mjradwin** [comment]
Fixed in 5.5.1

**Comment by meyer59** [comment]
Hi,
Thank you for the fix, it works great!
Unfortunately, I am still facing the same issue with the `LIGHT_CANDLES_TZEIS ` flag.
In the attached screenshot, you can see the Havdalah event with a mask value of `16389`. Or if you make 
` if(event.mask & flags.LIGHT_CANDLES_TZEIS)` you got 0 since `16389 & 32 => 0`
Steps to Reproduce:
Use a mask value of `16389`.
Attempt to use `if(event.mask & flags.LIGHT_CANDLES_TZEIS)` to detect the flag.
Notice that the `LIGHT_CANDLES_TZEIS ` flag is not detected (result = 0 ).
Thank you for your help! Let me know if you need further details.

**Comment by mjradwin** [comment]
Could you change your code to do this instead?

```js
if (event.mask & (flags.LIGHT_CANDLES_TZEIS | flags.YOM_TOV_ENDS)) {
  // ...
}
```

The reason this will work is that the `HavdalahEvent` for the end of Yom Kippur (and the end of any chag) will have `flags.YOM_TOV_ENDS` instead of `flags.LIGHT_CANDLES_TZEIS`

`flags.LIGHT_CANDLES_TZEIS` is currently used in two scenarios:

1. it indicates that candles should be lit for second day chag (in Diaspora) or second day Rosh Hashana (both Israel + Diaspora)
2. on Saturday night to indicate Havdalah time

We use the same `HavdalahEvent` for both end of Shabbat (with `flags.LIGHT_CANDLES_TZEIS`) and for end of holiday (with `flags.YOM_TOV_ENDS`)

**Comment by meyer59** [comment]
Hey
It works great, thanks

**Comment by meyer59** [comment]
thank you it works!
